app:
  title: Summer Framework
  version: ${VER:1.0}
summer:
  datasource:
    url: jdbc:mysql://localhost:3306/apseigyopoc
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 111111
